runtime: nodejs20
env: standard
instance_class: F2

env_variables:
  NODE_ENV: "production"

vpc_access_connector:
  name: projects/eventsiteresponsive/locations/us-west1/connectors/ae-connector

# Notes:
# - Created the connector ae-connector in us-west1 on the default VPC.
# - Combine with Cloud NAT to provide a static egress IP you can whitelist in Atlas.
# - Do NOT store secrets in this file. Use Secret Manager (the app loads secrets when
#   running in GCP via `backend/src/secrets.ts`).
handlers:
  - url: /.*
    script: auto